# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Week_12_MapLocation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week_12_MapLocation
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
end
